### ISSUE TITLE
Bug with Icons system

### ISSUE THREAD

**Issue by trevorbidlack** [march08/dashboard-ui-kit#17]
I have an issue where I cannot use the built in icon system with the following error upon page load:
![](https://i.imgur.com/1gb4tQ7.png)

I'm on next.js, though I don't think it's what's causing the issue.

Here's more info for context:

![](https://i.imgur.com/sZCg6QY.png)
![](https://i.imgur.com/Xwxwt8U.png)

Thanks in advance, the UI kit is great overall, despite this bug.

**Comment by fbrandt-dev** [comment]
For me it worked by importing:
`import Icon from "@duik/icon";`

**Comment by lowpolyfox** [comment]
You need to remove the brackets in order to import it correctly, otherwise the error will keep popping up.
