### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by andersryanc** [march08/dashboard-ui-kit#5]
I'm very much interested in using your UI Kit with Next.JS but the way you've used webpack to compile / bundle all the components, as soon as you import anything it throws an error (because of Server Side Rendering) which reads: `ReferenceError: window is not defined`.

**Comment by march08** [comment]
@andersryanc I am aware of it, the fixes should be easy enough to be resolved by EOW

**Comment by dternyak** [comment]
@march08 Any updates here? SSR would be very valuable :)

**Comment by lijy91** [comment]
Clone the repository to your computer and Modify `packages/webpack.config.js` file, add `globalObject: "this"` to output node.

```diff
...

module.exports = {
  output: {
    libraryTarget: "umd",
    filename: "[name]/dist/index.js",
-    path: path.resolve(__dirname)
-    path: path.resolve(__dirname),
+    globalObject: "this"
  },
};

...

```

**Comment by march08** [comment]
> @march08 Any updates here? SSR would be very valuable :)

Hey man, sorry I absolutely had no time. Can you check the latest version now?
