### ISSUE TITLE
webpack build errors / import resolve issues

### ISSUE THREAD

**Issue by andersryanc** [march08/dashboard-ui-kit#6]
I forked the repo and was trying to look into a way to fix my other issue (#5) but when I try and run the build script, I get the following error on every SCSS file:

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '@duik/core/_vars.scss';
^
      File to import not found or unreadable: @duik/core/_vars.scss.
```

I tried to add a `resolve.alias` setting to the `packages/webpack.config.js` but that didn't seem to help:

```
resolve: {
    extensions: [".tsx", ".ts", ".js"],
    alias: {
      "@duik": path.resolve(__dirname, 'packages/')
    }
  },
```

It seems like you must have some special configurations on your end (outside of the project files, etc)?

Also, this may or may not be related, but I'm also getting errors in VS Code in the typescript files about the imports:

<img width="853" alt="Screen Shot 2019-10-29 at 11 19 02 AM" src="https://user-images.githubusercontent.com/689046/67796829-ef860e80-fa3d-11e9-81c2-c5242195ead1.png">

**Comment by lijy91** [comment]
same problem, i found the solution, before `yarn build` you need to execute

```
$ npx lerna bootstrap
```
