### ISSUE TITLE
Invalid hook call. when using in next.js

### ISSUE THREAD

**Issue by lijy91** [march08/dashboard-ui-kit#8]
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

**Comment by march08** [comment]
> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

Can you provide me more details? When is that happening?

**Comment by lijy91** [comment]
I upgraded to 0.5.3 and the problem does not recur
