### ISSUE TITLE
Module not found: Error: Can't resolve './check'

### ISSUE THREAD

**Issue by lijy91** [march08/dashboard-ui-kit#9]
ERROR in ./packages/BaseInput/index.tsx
--
07:04:03 PM | Module not found: Error: Can't resolve './check' in '/zeit/53f9802/dashboard-ui-kit/packages/BaseInput'

**Comment by march08** [comment]
> ## ERROR in ./packages/BaseInput/index.tsx
> 07:04:03 PM | Module not found: Error: Can't resolve './check' in '/zeit/53f9802/dashboard-ui-kit/packages/BaseInput'

Thanks for the report. Can you try upgrading your package? It was a casing bug.. :)

**Comment by lijy91** [comment]
problem solved
